# Generated by Django 4.2 on 2025-05-11 15:59 (modified to skip table creation)

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("afriapp", "__first__"),
    ]

    operations = [
        # Empty operations list - this will effectively skip the table creation
        # since the tables were already created manually
    ]
