# Generated by Django 4.2 on 2024-10-27 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
