# Generated by Django 4.2.19 on 2025-02-21 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('afriapp', '0002_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='afriapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afriapp.product')),
            ],
        ),
    ]
