# Generated by Django 4.2 on 2025-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriapp', '0003_fix_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('newsletter_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('last_action', models.CharField(default='browse', max_length=50)),
                ('conversion_attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guest Profile',
                'verbose_name_plural': 'Guest Profiles',
            },
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
