# Generated by Django 5.2 on 2025-05-13 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0002_product_fields"),
        ("afriapp", "0003_product_sale_price"),
    ]

    operations = []
