# Generated by Django 5.2 on 2025-05-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0005_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
