# Generated by Django 4.2.19 on 2025-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriapp', '0005_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
