# Generated by Django 5.2 on 2025-05-14 01:07

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("afriapp", "0006_alter_customer_first_name_alter_customer_last_name_and_more"),
    ]

    operations = [
        # Ensure Customer table exists
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "afriapp_customer" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "first_name" varchar(100) NULL,
                "last_name" varchar(100) NULL,
                "email" varchar(254) NOT NULL UNIQUE,
                "phone_number" varchar(15) NULL,
                "address" text NULL,
                "city" varchar(100) NULL,
                "state" varchar(100) NULL,
                "postal_code" varchar(10) NULL,
                "country" varchar(100) NULL,
                "date_joined" datetime NOT NULL,
                "is_guest" bool NOT NULL,
                "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            "SELECT 1;"  # No-op for backwards migration
        ),
    ]
