# Generated by Django 4.2.19 on 2025-02-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afriapp', '0007_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='basket_no',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='pay_code',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
