# Generated by Django 5.2 on 2025-05-14 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0010_create_customer_table_manually"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "afriapp_shopcart" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "basket_no" varchar(36) NULL,
                "quantity" integer NOT NULL,
                "paid_order" bool NOT NULL,
                "date_added" datetime NOT NULL,
                "last_updated" datetime NOT NULL,
                "session_key" varchar(40) NULL,
                "customer_id" integer NULL REFERENCES "afriapp_customer" ("id") DEFERRABLE INITIALLY DEFERRED,
                "product_id" integer NOT NULL REFERENCES "afriapp_product" ("id") DEFERRABLE INITIALLY DEFERRED,
                "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            "SELECT 1;"
        ),
    ]
