# Generated by Django 5.2 on 2025-05-14 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afriapp", "0012_fix_customer_table"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- First, create the customer table if it doesn't exist
            CREATE TABLE IF NOT EXISTS "customer" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "first_name" varchar(100) NULL,
                "last_name" varchar(100) NULL,
                "email" varchar(254) NOT NULL UNIQUE,
                "phone_number" varchar(15) NULL,
                "address" text NULL,
                "city" varchar(100) NULL,
                "state" varchar(100) NULL,
                "postal_code" varchar(10) NULL,
                "country" varchar(100) NULL,
                "date_joined" datetime NOT NULL,
                "is_guest" bool NOT NULL DEFAULT 0,
                "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
            );

            -- Then, copy data from afriapp_customer to customer if afriapp_customer exists
            INSERT OR IGNORE INTO "customer" (
                "id", "first_name", "last_name", "email", "phone_number",
                "address", "city", "state", "postal_code", "country",
                "date_joined", "is_guest", "user_id"
            )
            SELECT
                "id", "first_name", "last_name", "email", "phone_number",
                "address", "city", "state", "postal_code", "country",
                "date_joined", "is_guest", "user_id"
            FROM "afriapp_customer"
            WHERE EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='afriapp_customer');
            """,
            "SELECT 1;"  # No-op for backwards migration
        ),
    ]
