# Generated by Django 4.2 on 2025-05-11 16:34

import agro_linker.models.market
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agro_linker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_conversion",
            field=models.JSONField(
                default=agro_linker.models.market.Product.default_unit_conversion,
                help_text="Conversion rates for different units",
            ),
        ),
    ]
